import '../app/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from './_components/footer/Footer';
import AuthModal from './_components/modals/AuthModal';
import ToasterProvider from './_providers/ToasterProvider';
import ClientOnly from './_components/clientOnly/ClientOnly';
import Header from './_components/header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        suppressHydrationWarning
        className={inter.className}
      >
        <div className='flex flex-col min-h-screen'>
          <ClientOnly>
            <ToasterProvider />
            <AuthModal />
            <Header />
          </ClientOnly>
          <main className='flex-grow p-6 lg:px-8'>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
